cas:
  #Required properties
  server-url-prefix: http://ids.ynu.edu.cn/authserver/
  server-login-url: http://ids.ynu.edu.cn/authserver/login
  client-host-url: http://cas.test.ynu.edu.cn

  #Optional properties
  authentication-url-patterns: [/protected, /protected2]
  validation-url-patterns: [/protected, /protected2]
  #request-wrapper-url-patterns: [/protected, /protected2]
  #assertion-thread-local-url-patterns: [/*]

  #One of CAS3, CAS, or SAML. The default is CAS3 if not explicitly specified
  validation-type: CAS3

  #gateway: true
  use-session: true
  #redirect-after-validation: false
  #allowed-proxy-chains: ['https://dk.example.org:8443/proxy1', 'https://dk.example.org:8443/proxy2']
  #proxy-callback-url: https://dk.example.org:8443/proxy-callback
  #proxy-receptor-url: /proxy-callback
  #accept-any-proxy: true

casLogoutUrl: http://ids.ynu.edu.cn/authserver/logout

spring:
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

#Sample embedded servlet container SSL config and session tracking mode. Change as appropriate for your local deployment environment
#server:
#  port: 8443
#  session:
#    cookie:
#      http-only: true
#    tracking-modes: COOKIE
#  ssl:
#    enabled: true
#    key-store: /Users/dima767/.keystore
#    key-store-password: changeit
#    trust-store: /Users/dima767/.keystore
#    trust-store-password: changeit
  #For 'renew' param, latest Java CAS client requires that it is set as the Servlet 'context-param'. This is how to easily set it in Spring Boot
  #context-parameters.renew: true


logging.level:
    org.jasig.cas: DEBUG
